# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/ostrichserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/ostrichserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ostrichserver/CMakeFiles /root/ostrichserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ostrichserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named os

# Build rule for target.
os: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os
.PHONY : os

# fast build rule for target.
os/fast:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/build
.PHONY : os/fast

acceptor.o: acceptor.c.o
.PHONY : acceptor.o

# target to build an object file
acceptor.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/acceptor.c.o
.PHONY : acceptor.c.o

acceptor.i: acceptor.c.i
.PHONY : acceptor.i

# target to preprocess a source file
acceptor.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/acceptor.c.i
.PHONY : acceptor.c.i

acceptor.s: acceptor.c.s
.PHONY : acceptor.s

# target to generate assembly for a file
acceptor.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/acceptor.c.s
.PHONY : acceptor.c.s

access_log.o: access_log.c.o
.PHONY : access_log.o

# target to build an object file
access_log.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/access_log.c.o
.PHONY : access_log.c.o

access_log.i: access_log.c.i
.PHONY : access_log.i

# target to preprocess a source file
access_log.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/access_log.c.i
.PHONY : access_log.c.i

access_log.s: access_log.c.s
.PHONY : access_log.s

# target to generate assembly for a file
access_log.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/access_log.c.s
.PHONY : access_log.c.s

config_parser.o: config_parser.c.o
.PHONY : config_parser.o

# target to build an object file
config_parser.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/config_parser.c.o
.PHONY : config_parser.c.o

config_parser.i: config_parser.c.i
.PHONY : config_parser.i

# target to preprocess a source file
config_parser.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/config_parser.c.i
.PHONY : config_parser.c.i

config_parser.s: config_parser.c.s
.PHONY : config_parser.s

# target to generate assembly for a file
config_parser.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/config_parser.c.s
.PHONY : config_parser.c.s

core_log.o: core_log.c.o
.PHONY : core_log.o

# target to build an object file
core_log.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/core_log.c.o
.PHONY : core_log.c.o

core_log.i: core_log.c.i
.PHONY : core_log.i

# target to preprocess a source file
core_log.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/core_log.c.i
.PHONY : core_log.c.i

core_log.s: core_log.c.s
.PHONY : core_log.s

# target to generate assembly for a file
core_log.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/core_log.c.s
.PHONY : core_log.c.s

error_log.o: error_log.c.o
.PHONY : error_log.o

# target to build an object file
error_log.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/error_log.c.o
.PHONY : error_log.c.o

error_log.i: error_log.c.i
.PHONY : error_log.i

# target to preprocess a source file
error_log.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/error_log.c.i
.PHONY : error_log.c.i

error_log.s: error_log.c.s
.PHONY : error_log.s

# target to generate assembly for a file
error_log.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/error_log.c.s
.PHONY : error_log.c.s

event.o: event.c.o
.PHONY : event.o

# target to build an object file
event.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/event.c.o
.PHONY : event.c.o

event.i: event.c.i
.PHONY : event.i

# target to preprocess a source file
event.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/event.c.i
.PHONY : event.c.i

event.s: event.c.s
.PHONY : event.s

# target to generate assembly for a file
event.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/event.c.s
.PHONY : event.c.s

eventpoll.o: eventpoll.c.o
.PHONY : eventpoll.o

# target to build an object file
eventpoll.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/eventpoll.c.o
.PHONY : eventpoll.c.o

eventpoll.i: eventpoll.c.i
.PHONY : eventpoll.i

# target to preprocess a source file
eventpoll.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/eventpoll.c.i
.PHONY : eventpoll.c.i

eventpoll.s: eventpoll.c.s
.PHONY : eventpoll.s

# target to generate assembly for a file
eventpoll.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/eventpoll.c.s
.PHONY : eventpoll.c.s

evthread.o: evthread.c.o
.PHONY : evthread.o

# target to build an object file
evthread.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/evthread.c.o
.PHONY : evthread.c.o

evthread.i: evthread.c.i
.PHONY : evthread.i

# target to preprocess a source file
evthread.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/evthread.c.i
.PHONY : evthread.c.i

evthread.s: evthread.c.s
.PHONY : evthread.s

# target to generate assembly for a file
evthread.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/evthread.c.s
.PHONY : evthread.c.s

memory.o: memory.c.o
.PHONY : memory.o

# target to build an object file
memory.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/memory.c.o
.PHONY : memory.c.o

memory.i: memory.c.i
.PHONY : memory.i

# target to preprocess a source file
memory.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/memory.c.i
.PHONY : memory.c.i

memory.s: memory.c.s
.PHONY : memory.s

# target to generate assembly for a file
memory.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/memory.c.s
.PHONY : memory.c.s

netevent.o: netevent.c.o
.PHONY : netevent.o

# target to build an object file
netevent.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/netevent.c.o
.PHONY : netevent.c.o

netevent.i: netevent.c.i
.PHONY : netevent.i

# target to preprocess a source file
netevent.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/netevent.c.i
.PHONY : netevent.c.i

netevent.s: netevent.c.s
.PHONY : netevent.s

# target to generate assembly for a file
netevent.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/netevent.c.s
.PHONY : netevent.c.s

os.o: os.c.o
.PHONY : os.o

# target to build an object file
os.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/os.c.o
.PHONY : os.c.o

os.i: os.c.i
.PHONY : os.i

# target to preprocess a source file
os.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/os.c.i
.PHONY : os.c.i

os.s: os.c.s
.PHONY : os.s

# target to generate assembly for a file
os.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/os.c.s
.PHONY : os.c.s

signal.o: signal.c.o
.PHONY : signal.o

# target to build an object file
signal.c.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/signal.c.o
.PHONY : signal.c.o

signal.i: signal.c.i
.PHONY : signal.i

# target to preprocess a source file
signal.c.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/signal.c.i
.PHONY : signal.c.i

signal.s: signal.c.s
.PHONY : signal.s

# target to generate assembly for a file
signal.c.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/signal.c.s
.PHONY : signal.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... os"
	@echo "... rebuild_cache"
	@echo "... acceptor.o"
	@echo "... acceptor.i"
	@echo "... acceptor.s"
	@echo "... access_log.o"
	@echo "... access_log.i"
	@echo "... access_log.s"
	@echo "... config_parser.o"
	@echo "... config_parser.i"
	@echo "... config_parser.s"
	@echo "... core_log.o"
	@echo "... core_log.i"
	@echo "... core_log.s"
	@echo "... error_log.o"
	@echo "... error_log.i"
	@echo "... error_log.s"
	@echo "... event.o"
	@echo "... event.i"
	@echo "... event.s"
	@echo "... eventpoll.o"
	@echo "... eventpoll.i"
	@echo "... eventpoll.s"
	@echo "... evthread.o"
	@echo "... evthread.i"
	@echo "... evthread.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... netevent.o"
	@echo "... netevent.i"
	@echo "... netevent.s"
	@echo "... os.o"
	@echo "... os.i"
	@echo "... os.s"
	@echo "... signal.o"
	@echo "... signal.i"
	@echo "... signal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

