# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/ostrichserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/ostrichserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ostrichserver/CMakeFiles /root/ostrichserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/ostrichserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named os

# Build rule for target.
os: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 os
.PHONY : os

# fast build rule for target.
os/fast:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/build
.PHONY : os/fast

# target to build an object file
access_log.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/access_log.o
.PHONY : access_log.o

# target to preprocess a source file
access_log.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/access_log.i
.PHONY : access_log.i

# target to generate assembly for a file
access_log.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/access_log.s
.PHONY : access_log.s

# target to build an object file
config_parser.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/config_parser.o
.PHONY : config_parser.o

# target to preprocess a source file
config_parser.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/config_parser.i
.PHONY : config_parser.i

# target to generate assembly for a file
config_parser.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/config_parser.s
.PHONY : config_parser.s

# target to build an object file
core_log.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/core_log.o
.PHONY : core_log.o

# target to preprocess a source file
core_log.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/core_log.i
.PHONY : core_log.i

# target to generate assembly for a file
core_log.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/core_log.s
.PHONY : core_log.s

# target to build an object file
error_log.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/error_log.o
.PHONY : error_log.o

# target to preprocess a source file
error_log.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/error_log.i
.PHONY : error_log.i

# target to generate assembly for a file
error_log.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/error_log.s
.PHONY : error_log.s

# target to build an object file
memory.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/memory.o
.PHONY : memory.o

# target to preprocess a source file
memory.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/memory.i
.PHONY : memory.i

# target to generate assembly for a file
memory.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/memory.s
.PHONY : memory.s

# target to build an object file
os.o:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/os.o
.PHONY : os.o

# target to preprocess a source file
os.i:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/os.i
.PHONY : os.i

# target to generate assembly for a file
os.s:
	$(MAKE) -f CMakeFiles/os.dir/build.make CMakeFiles/os.dir/os.s
.PHONY : os.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... os"
	@echo "... rebuild_cache"
	@echo "... access_log.o"
	@echo "... access_log.i"
	@echo "... access_log.s"
	@echo "... config_parser.o"
	@echo "... config_parser.i"
	@echo "... config_parser.s"
	@echo "... core_log.o"
	@echo "... core_log.i"
	@echo "... core_log.s"
	@echo "... error_log.o"
	@echo "... error_log.i"
	@echo "... error_log.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... os.o"
	@echo "... os.i"
	@echo "... os.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

